# Generated by Django 3.0.6 on 2020-05-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='owner',
        ),
    ]
