# Generated by Django 3.0.6 on 2020-06-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200621_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruction',
            unique_together={('recipe', 'order')},
        ),
    ]
